### PR TITLE
Fix send photo bug

### LINKED ISSUE #8: Forwarded images are very low res
Suspect this is caused by forwarding the thumbnail instead

### PR DESCRIPTION
**Pull request by gnahzeus**
Fix photo bug

### CODE REVIEW

File: src/commands.js [hunk 1]
```diff
@@ -110,7 +110,8 @@ PhotoHandler = async (ctx) => {
     const caption = ctx.message.caption || ""
     const target = ctx.isAngel ? ctx.angel : ctx.mortal
     if (target.isRegistered()) {
-        const fileLink = await ctx.telegram.getFileLink(photos[0].file_id)
+        const len = ctx.message.photo.length - 1
```
Comment (nicktohzyu) [inline src/commands.js]: could you please add a brief comment explaining what this photos (array?) is, eg how many items we expect there are

Comment (nicktohzyu) [inline src/commands.js]: Oof please don't do this! Because it would be wrong to say that this is the length of photos. Instead, a better way could be
```
const len = ctx.message.photo.length
const fileLink = await ctx.telegram.getFileLink(photos[len-1].file_id)
```

**Review by nicktohzyu — CHANGES_REQUESTED** [review]
Please exclude package-lock changes!

**Review by nicktohzyu — APPROVED** [review]
